# Generated by Django 3.2.21 on 2023-09-30 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Katte', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dokode',
            new_name='Doko',
        ),
        migrations.RenameField(
            model_name='doko',
            old_name='Dokode',
            new_name='Doko',
        ),
    ]
