# Generated by Django 3.2.21 on 2023-09-30 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Katte', '0002_auto_20230930_0302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doko',
            new_name='Dokode',
        ),
        migrations.RenameField(
            model_name='dokode',
            old_name='Doko',
            new_name='Dokode',
        ),
    ]
