# Generated by Django 3.2.21 on 2023-09-30 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Katte', '0003_auto_20230930_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dokode',
            old_name='Dokode',
            new_name='Doko',
        ),
    ]
